rvm:
  - 2.3.0
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.1 libpq-dev
before_script:
  - psql -c 'create database "printer-test";' -U postgres
  - psql -c 'create database "printer";' -U postgres

